sudo: false
matrix:
  fast_finish: true
  include:
  - env: PYCBC_CONTAINER=build_and_test LAL_DATA_PATH=$TRAVIS_BUILD_DIR LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR PYTHON3='TRUE'
    language: python
    python: 3.7
install:
- pip install --upgrade setuptools pip
- pip install numpy --upgrade
script:
- python t.py

