language: python
jobs:
  include:
  - python: "3.6"
    env: NUMPY_VERSION=1.19.0
  - python: "3.7"
    env: NUMPY_VERSION=1.19.0
  - python: "3.7"
    env: NUMPY_VERSION=1.18.5
install:
- pip install --upgrade setuptools pip
- pip install "numpy==${NUMPY_VERSION}"
- python t.py

